### ISSUE TITLE
Repository with GWT 2.8.2-rx1 is returning 400 Bad Request

### ISSUE THREAD

**Issue by trohr** [intendia-oss/rxjava-gwt#5]
Hello,

the repository that is required to use GWT 2.8.2-rx1 is not working right now.
Accessing URL `https://raw.githubusercontent.com/intendia-oss/rxjava-gwt/mvn-repo/` returns `400: Bad Request` with no detail on how to fix it.

Can you please advice on how to fix the problem or fix it yourselves?
Thank you.

Sincerely yours,
Tomas Rohrbacher

**Comment by ibaca** [comment]
It is working, but you can not explore each folder, you can only access to actual files, for example, this one:
https://raw.githubusercontent.com/intendia-oss/rxjava-gwt/mvn-repo/com/google/gwt/gwt/2.8.2-rx1/gwt-2.8.2-rx1.pom

Do you have any problems using this repo in maven?
