### ISSUE TITLE
Update for GWT 2.9

### ISSUE THREAD

**Issue by lofidewanto** [intendia-oss/rxjava-gwt#6]
Hi @ibaca,

I'm updating GWT Boot for GWT 2.9 and elemento-core 1.0.1. See: https://github.com/gwtboot/gwt-boot-modules/issues/13 and https://github.com/gwtboot/gwt-boot-samples/issues/11

Is there any update on rxjava for GWT 2.9? At the moment I'm using gwt 2.8.2-rx1 and rx-gwt 2.2.

Thanks,
Lofi

**Comment by ibaca** [comment]
oh, of course, the library (rxjava-gwt) doesn't require any change, but if you use GWT 2.9 you don't need the custom GWT 2.8-rx anymore 🙌 I updated the tutorial (https://dev.to/ibaca/modern-gwt-first-steps-509k), which uses rxjava, the same day GWT 2.9 was released! hehe using the custom version (2.8-rx) was very ugly!

I'm going to update the readme 👍

**Comment by lofidewanto** [comment]
Great to hear, so I will try it.
